name: DeployProject

on: [push]


jobs:
    BuildFrontend:
        runs-on: ubuntu-latest

        steps:
            - name: say hello
              run: echo "hello world"


         
